name: End-to-end tests
on:
  push:
  workflow_dispatch:

jobs:
  playwright-replayio:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Install Replay Chromium
      run: npx replayio install

    - name: Run Playwright tests
      run: npm test
      env:
        REPLAY_API_KEY: ${{ secrets.REPLAY_API_KEY }}
